#ifndef LIFT_SQLITE_ADAPTER_GLOBAL_H
#define LIFT_SQLITE_ADAPTER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIFT_SQLITE_ADAPTER_LIBRARY)
#  define LIFT_SQLITE_ADAPTER_EXPORT Q_DECL_EXPORT
#else
#  define LIFT_SQLITE_ADAPTER_EXPORT Q_DECL_IMPORT
#endif

#endif // LIFT_SQLITE_ADAPTER_GLOBAL_H
